### ISSUE TITLE
Disable safari default details marker

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingaweb2-module-businessprocess#406]
## Describe the bug

Currently, both the default detail marker and the custom caret icons are rendered, which looks quite weird on Safari. We should disable the default Safari detail marker as we use our own icons to represent the detail state.

<img width="1248" alt="Bildschirmfoto 2023-08-15 um 10 57 45" src="https://github.com/Icinga/icingaweb2-module-businessprocess/assets/57616252/e471022f-3170-45d6-8eb9-92b3f5baa8fa">

This should do the trick:
```css
li.process summary::-webkit-details-marker {
    display: none;
}
```
